/** Application record shapes retained through the local MongoDB migration. */
export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[];
export type MongoCollections = {
  author_directions: {
    body: string;
    chapter_id: string | null;
    confirmed: boolean;
    created_at: string;
    id: string;
    is_inferred: boolean;
    kind: string;
    project_id: string;
    scene_id: string | null;
    scope: string;
    status: string;
    subject: string | null;
    updated_at: string;
  };
  chapters: {
    created_at: string;
    deleted_at: string | null;
    id: string;
    position: number;
    project_id: string;
    title: string;
    updated_at: string;
  };
  observations: {
    body: string;
    created_at: string;
    evidence: { scene_id: string; quote: string }[];
    id: string;
    kind: string;
    origin: string;
    project_id: string;
    scene_id: string | null;
    status: string;
    title: string;
    uncertainty: string | null;
    updated_at: string;
    why_it_matters: string | null;
  };
  outline_beats: {
    author_confirmed: boolean;
    chapter_id: string | null;
    created_at: string;
    id: string;
    intent: string | null;
    kind: string;
    link_basis: string;
    link_note: string | null;
    position: number;
    project_id: string;
    scene_id: string | null;
    status: string;
    title: string;
    updated_at: string;
  };
  projects: {
    created_at: string;
    creative_direction: string | null;
    deleted_at: string | null;
    genre: string | null;
    id: string;
    is_sample: boolean;
    owner_id: string;
    title: string;
    updated_at: string;
  };
  relationship_beats: {
    author_confirmed: boolean;
    change: string;
    created_at: string;
    evidence: { scene_id: string; quote: string }[];
    id: string;
    project_id: string;
    relationship_id: string;
    scene_id: string | null;
    story_position: number | null;
    truth_type: string;
    updated_at: string;
  };
  research_notes: {
    body: string;
    created_at: string;
    id: string;
    kind: string;
    link: string | null;
    project_id: string;
    tags: string[];
    title: string;
    updated_at: string;
  };
  scene_revisions: {
    content: Json | null;
    created_at: string;
    id: string;
    label: string | null;
    plain_text: string;
    project_id: string;
    scene_id: string;
    source: string;
    word_count: number;
  };
  scenes: {
    chapter_id: string;
    content: Json | null;
    created_at: string;
    deleted_at: string | null;
    id: string;
    location: string | null;
    plain_text: string;
    position: number;
    pov: string | null;
    project_id: string;
    story_time: string | null;
    summary: string | null;
    title: string;
    updated_at: string;
    word_count: number;
  };
  story_claims: {
    assertion: string;
    author_confirmed: boolean;
    basis: string;
    claim_kind: string;
    created_at: string;
    entity_id: string | null;
    evidence: { scene_id: string; quote: string }[];
    id: string;
    knowledge_holder: string | null;
    knowledge_state: string | null;
    project_id: string;
    revision_id: string | null;
    scene_id: string | null;
    story_position: number | null;
    subject: string;
    truth_type: string;
    updated_at: string;
    validity: string;
  };
  story_entities: {
    aliases: string[];
    author_confirmed: boolean;
    created_at: string;
    current_state: string | null;
    first_scene_id: string | null;
    id: string;
    identity: string | null;
    kind: string;
    name: string;
    notes: string | null;
    project_id: string;
    truth_type: string;
    updated_at: string;
  };
  story_events: {
    author_confirmed: boolean;
    certainty: string;
    created_at: string;
    evidence: { scene_id: string; quote: string }[];
    id: string;
    order_hint: number;
    origin: string;
    project_id: string;
    scene_id: string | null;
    summary: string;
    truth_type: string;
    updated_at: string;
    when_text: string | null;
  };
  story_possibilities: {
    changes: Json;
    consequences: Json;
    created_at: string;
    id: string;
    name: string;
    notes: string | null;
    origin: string;
    premise: string;
    project_id: string;
    scene_id: string | null;
    status: string;
    updated_at: string;
  };
  story_promises: {
    author_confirmed: boolean;
    created_at: string;
    entity_id: string | null;
    id: string;
    origin: string;
    payoff_quote: string | null;
    payoff_scene_id: string | null;
    project_id: string;
    promise: string;
    setup_quote: string | null;
    setup_scene_id: string | null;
    status: string;
    subject: string | null;
    title: string;
    truth_type: string;
    updated_at: string;
  };
  story_relationships: {
    author_confirmed: boolean;
    created_at: string;
    current_state: string | null;
    from_entity_id: string;
    id: string;
    nature: string | null;
    notes: string | null;
    project_id: string;
    to_entity_id: string;
    truth_type: string;
    updated_at: string;
  };
  story_synopses: {
    body: string;
    created_at: string;
    id: string;
    locked: boolean;
    project_id: string;
    scope: string;
    source: string;
    target_id: string | null;
    updated_at: string;
  };
  story_thread_beats: {
    author_confirmed: boolean;
    created_at: string;
    evidence: { scene_id: string; quote: string }[];
    id: string;
    note: string;
    project_id: string;
    role: string;
    scene_id: string | null;
    story_position: number | null;
    thread_id: string;
    truth_type: string;
    updated_at: string;
  };
  story_threads: {
    author_confirmed: boolean;
    created_at: string;
    id: string;
    kind: string;
    name: string;
    notes: string | null;
    origin: string;
    position: number;
    premise: string;
    project_id: string;
    status: string;
    truth_type: string;
    updated_at: string;
  };
};
